### ISSUE TITLE
ValidationException: Autodetect language is not supported.

### ISSUE THREAD

**Issue by fmalothomas** [GenesysCloudBlueprints/chat-translator-blueprint#9]
Hello, I've been trying to run this application but I keep getting this exception and I can't find a solution.

```bash
/chat-translator-blueprint/run-local.js
HTTPS listening on: 443
ValidationException: Autodetect language is not supported.
    at deserializeAws_json1_1TranslateTextCommandError (/home/fmalothomas/WebstormProjects/chat-translator-blueprint/node_modules/@aws-sdk/client-translate/dist/cjs/protocols/Aws_json1_1.js:1088:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/fmalothomas/WebstormProjects/chat-translator-blueprint/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /home/fmalothomas/WebstormProjects/chat-translator-blueprint/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/home/fmalothomas/WebstormProjects/chat-translator-blueprint/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /home/fmalothomas/WebstormProjects/chat-translator-blueprint/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22 {
  __type: 'ValidationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '307bc929-d6ac-4b0a-ad4d-657a02b15620',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

```

**Comment by DanteCady** [comment]
Hey,

I have been having trouble getting this to work on an Azure App Service. I do have the service running but I notice for some odd reason it will not access the account creds from the .env, can you provide some input on how you got it work?
